export const mockData = {
  request: {
    type: 'City',
    query: 'Melbourne, Australia',
    language: 'en',
    unit: 'm',
  },
  location: {
    name: 'Melbourne',
    country: 'Australia',
    region: 'Victoria',
    lat: '-37.817',
    lon: '144.967',
    timezone_id: 'Australia/Melbourne',
    localtime: '2020-11-14 14:00',
    localtime_epoch: 1605362400,
    utc_offset: '11.0',
  },
  current: {
    observation_time: '03:00 AM',
    temperature: 19,
    weather_code: 113,
    weather_icons: [
      'https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0001_sunny.png',
    ],
    weather_descriptions: ['Sunny'],
    wind_speed: 9,
    wind_degree: 290,
    wind_dir: 'WNW',
    pressure: 1010,
    precip: 0,
    humidity: 46,
    cloudcover: 0,
    feelslike: 19,
    uv_index: 5,
    visibility: 10,
    is_day: 'yes',
  },
};
